Repository sugiyem/Chattoku, pull requests merged in 2022-07, with the labels that each got.

#64 Add Loading Animation
  src/components/Miscellaneous/LoaderAnimation.js
  src/components/Miscellaneous/Loading.js
Labels: enhancement

#59 Add group admin
  __test__/Helper.js
  __test__/__snapshots__/App.test.js.snap
  __test__/unit-test/Friend/FetchGroup.test.js
  __test__/unit-test/Friend/FetchGroupAdmin.test.js
  __test__/unit-test/Friend/HandleGroup.test.js
  __test__/unit-test/Friend/HandleGroupAdmin.test.js
  app.config.js
  src/components/Friend/AddMemberComponent.js
  src/components/Friend/ContactBar.js
  src/components/Friend/ContactButtonGroup.js
  src/components/Friend/EditMemberComponent.js
  src/components/Friend/GroupAdminButtons.js
  src/components/Friend/GroupMemberList.js
  src/components/Friend/GroupOwnerButtons.js
  src/components/Friend/RenderGroupDetail.js
  src/components/Friend/RenderGroupLists.js
  src/components/Miscellaneous/Caution.js
  src/components/Miscellaneous/NotificationText.js
  src/constants/Group.js
  src/screens/Friend/AddGroupMemberScreen.js
  src/screens/Friend/EditGroupMemberScreen.js
  src/screens/Friend/EditPendingGroupMemberScreen.js
  src/screens/Friend/FriendScreen.js
  src/screens/Friend/GroupInfoScreen.js
  src/screens/Friend/GroupListScreen.js
  src/screens/Friend/GroupRequestInfoScreen.js
  src/screens/Friend/GroupRequestsScreen.js
  src/services/Friend/FetchGroup.js
  src/services/Friend/FetchGroupAdmin.js
  src/services/Friend/HandleGroup.js
  src/services/Friend/HandleGroupAdmin.js
  src/services/Friend/Sorter.js
  src/styles/GeneralStyles.js
  src/styles/InfoStyles.js
Labels: bug, enhancement, testing

#67 Add forum profile popup
  src/components/Forum/ForumComment/CommentCard.js
  src/components/Forum/ForumPost/PostCard.js
  src/components/Forum/ProfileOverlay.js
  src/components/Forum/RenderFriendSection.js
  src/screens/Chat/ChatDetailScreen.js
  src/screens/Forum/ForumPostScreen.js
  src/screens/Forum/ForumScreen.js
  src/screens/Forum/overlayContext.js
  src/services/Profile/FetchUserInfo.js
Labels: bug, enhancement

#66 Additional chat features
  __test__/Helper.js
  __test__/unit-test/Chat/FetchActiveChats.test.js
  __test__/unit-test/Chat/HandleChat.test.js
  __test__/unit-test/Chat/HandleSystemMessage.test.js
  __test__/unit-test/Friend/FetchGroup.test.js
  src/components/Chat/ActiveChatLists.js
  src/components/Chat/BlockIcon.js
  src/components/Chat/ChatAvatar.js
  src/components/Chat/ChatBar.js
  src/components/Chat/ChatBubble.js
  src/components/Chat/ChatButtonGroup.js
  src/components/Chat/ChatHeader.js
  src/components/Chat/ChatModal.js
  src/components/Chat/ChatSections.js
  src/components/Chat/EditFriendIcon.js
  src/components/Forum/ProfileOverlay.js
  src/components/Friend/RenderGroupLists.js
  src/components/Friend/RenderUserLists.js
  src/screens/Chat/ChatDetailScreen.js
  src/screens/Chat/ChatListScreen.js
  src/screens/Chat/GroupChatDetailScreen.js
  src/screens/Chat/GroupChatListScreen.js
  src/services/Chat/FetchActiveChats.js
  src/services/Chat/HandleChat.js
  src/services/Chat/HandleSystemMessage.js
  src/services/Friend/HandleGroup.js
  src/services/Profile/FetchUserInfo.js
  src/styles/ChatStyles.js
Labels: enhancement, testing

#72 Sort by timestamp
  package.json
  src/components/Forum/ForumComment/CommentCard.js
  src/components/Forum/ForumComment/CommentList.js
  src/components/Forum/ForumPost/PostCard.js
  src/components/Forum/ForumPost/PostList.js
  src/screens/Forum/ForumPostScreen.js
  src/screens/Forum/ForumScreen.js
  src/services/Forum/FetchComment.js
  src/services/Forum/FetchPost.js
  src/services/Forum/HandleComment.js
  src/services/Forum/HandleForumPost.js
  yarn.lock
Labels: bug, enhancement

#75 Update profile overlay
  src/components/Forum/ProfileOverlay.js
Labels: enhancement

#77 Firebase optimization
  src/components/Miscellaneous/EditSection.js
  src/components/Miscellaneous/UploadImageModal.js
  src/services/Friend/FetchBlockedUsers.js
  src/services/Friend/FetchFriendStatus.js
  src/services/Friend/FetchGroup.js
  src/services/Miscellaneous/HandleImage.js
Labels: enhancement

#78 Forum image upload
  src/components/Forum/ForumPost/PostCard.js
  src/components/Forum/ForumPost/PostList.js
  src/components/Forum/ForumPost/RenderPostScreen.js
  src/components/Miscellaneous/ImageSlider.js
  src/screens/Forum/ForumPostScreen.js
  src/services/Miscellaneous/HandleImage.js
Labels: enhancement

#87 Fix add group member bug
  __test__/ui-test/Friend/AddGroupMemberScreen.test.js
  __test__/ui-test/Friend/AddMemberComponent.test.js
  src/components/Friend/AddMemberComponent.js
  src/components/Friend/EditMemberComponent.js
  src/screens/Friend/AddGroupMemberScreen.js
  src/screens/Friend/EditGroupMemberScreen.js
  src/screens/Friend/GroupInfoScreen.js
  src/services/Friend/GroupRole.js
  src/services/Friend/Sorter.js
Labels: bug, testing

#85 Forum unit test
  __test__/Helper.js
  __test__/unit-test/Forum/FetchComment.test.js
  __test__/unit-test/Forum/FetchFollowedForumData.test.js
  __test__/unit-test/Forum/FetchForumData.test.js
  __test__/unit-test/Forum/FetchPost.test.js
  __test__/unit-test/Forum/FetchPreviousPosts.test.js
  __test__/unit-test/Forum/HandleBannedUsers.test.js
  __test__/unit-test/Forum/HandleComment.test.js
  __test__/unit-test/Forum/HandleForum.test.js
  __test__/unit-test/Forum/HandleForumAdmin.test.js
  __test__/unit-test/Forum/HandleForumPost.test.js
  __test__/unit-test/Forum/NotifyAllFollowers.test.js
  src/services/Forum/FetchComment.js
  src/services/Forum/FetchFollowedForumData.js
  src/services/Forum/FetchForumData.js
  src/services/Forum/FetchPost.js
  src/services/Forum/FetchPreviousPosts.js
  src/services/Forum/HandleBannedUsers.js
  src/services/Forum/HandleComment.js
  src/services/Forum/HandleForum.js
  src/services/Forum/HandleForumAdmin.js
  src/services/Forum/HandleForumPost.js
  src/services/Forum/NotifyAllFollowers.js
Labels: testing

#89 Add delete account functionality
  src/components/Chat/ChatModal.js
  src/components/Chat/ChatSections.js
  src/components/Forum/ForumComment/CommentCard.js
  src/components/Forum/ForumManagement/RenderUserToManage.js
  src/components/Forum/ForumPost/PostCard.js
  src/components/Forum/ProfileOverlay.js
  src/constants/Batch.js
  src/screens/Forum/ForumPostScreen.js
  src/screens/Profile/ProfileHomeScreen.js
  src/services/Authentication/HandleAuthentication.js
  src/services/Chat/FetchActiveChats.js
  src/services/Forum/HandleBannedUsers.js
  src/services/Forum/HandleForumAdmin.js
  src/services/Friend/FetchFriendStatus.js
  src/services/Friend/HandleGroup.js
  src/services/Profile/FetchUserInfo.js
Labels: enhancement

#74 Add chat UI test
  __test__/ui-test/Chat/ActiveChatLists.test.js
  __test__/ui-test/Chat/BlockIcon.test.js
  __test__/ui-test/Chat/ChatAvatar.test.js
  __test__/ui-test/Chat/ChatBar.test.js
  __test__/ui-test/Chat/ChatBubble.test.js
  __test__/ui-test/Chat/ChatButtonGroup.test.js
  __test__/ui-test/Chat/ChatDetailScreen.test.js
  __test__/ui-test/Chat/ChatHeader.test.js
  __test__/ui-test/Chat/ChatInputBar.test.js
  __test__/ui-test/Chat/ChatListScreen.test.js
  __test__/ui-test/Chat/ChatModal.test.js
  __test__/ui-test/Chat/ChatSections.test.js
  __test__/ui-test/Chat/EditFriendIcon.test.js
  __test__/ui-test/Chat/GroupChatDetailScreen.test.js
  __test__/ui-test/Chat/GroupChatListScreen.test.js
  __test__/ui-test/Chat/__snapshots__/ActiveChatLists.test.js.snap
  __test__/ui-test/Chat/__snapshots__/ChatDetailScreen.test.js.snap
  __test__/ui-test/Chat/__snapshots__/ChatSections.test.js.snap
  __test__/ui-test/Chat/__snapshots__/GroupChatDetailScreen.test.js.snap
  __test__/unit-test/Forum/HandleBannedUsers.test.js
  src/components/Chat/BlockIcon.js
  src/components/Chat/ChatAvatar.js
  src/components/Chat/ChatBar.js
  src/components/Chat/ChatBubble.js
  src/components/Chat/ChatButtonGroup.js
  src/components/Chat/ChatHeader.js
  src/components/Chat/ChatInputBar.js
  src/components/Chat/ChatModal.js
  src/components/Chat/EditFriendIcon.js
  src/screens/Chat/ChatDetailScreen.js
  src/screens/Chat/ChatListScreen.js
  src/screens/Chat/GroupChatDetailScreen.js
  src/screens/Chat/GroupChatListScreen.js
  src/services/Forum/HandleBannedUsers.js
  src/services/Forum/HandleForumAdmin.js
  src/services/Profile/FetchUserInfo.js
Labels: testing

#95 Forum styling
  src/components/Forum/ForumCard.js
  src/components/Forum/ForumComment/CommentList.js
  src/components/Forum/ForumComment/RenderCommentScreen.js
  src/components/Forum/ForumHeader.js
  src/components/Forum/ForumList.js
  src/components/Forum/ForumPost/MainPostCard.js
  src/components/Forum/ForumPost/RenderPostScreen.js
  src/components/Forum/RenderManageForumDetails.js
  src/screens/Forum/FollowedForumScreen.js
  src/screens/Forum/ForumHomeScreen.js
  src/screens/Forum/ForumManagement/AddAdminScreen.js
  src/screens/Forum/ForumManagement/AddBannedScreen.js
  src/screens/Forum/ForumManagement/AdminsScreen.js
  src/screens/Forum/ForumManagement/BannedUsersScreen.js
  src/screens/Forum/ForumManagement/ManageForumScreen.js
  src/screens/Forum/ForumPostScreen.js
  src/screens/Forum/ForumScreen.js
  src/styles/ForumStyles.js
  src/styles/GeneralStyles.js
Labels: enhancement

#97 Friend section styling
  __test__/ui-test/Friend/ContactButtonGroup.test.js
  __test__/ui-test/Friend/FriendListScreen.test.js
  __test__/ui-test/Friend/FriendRequestsReceivedScreen.test.js
  __test__/ui-test/Friend/FriendRequestsSentScreen.test.js
  __test__/ui-test/Friend/__snapshots__/EditGroupScreen.test.js.snap
  __test__/ui-test/Friend/__snapshots__/GroupCreationScreen.test.js.snap
  __test__/ui-test/Friend/__snapshots__/GroupInfoScreen.test.js.snap
  __test__/ui-test/Friend/__snapshots__/GroupRequestInfoScreen.test.js.snap
  __test__/ui-test/Friend/__snapshots__/RenderGroupLists.test.js.snap
  __test__/ui-test/Friend/__snapshots__/RenderUserLists.test.js.snap
  src/components/Friend/AddMemberComponent.js
  src/components/Friend/ContactBar.js
  src/components/Friend/ContactButtonGroup.js
  src/components/Friend/EditMemberComponent.js
  src/components/Friend/GroupMemberList.js
  src/components/Friend/RenderFriendFavorites.js
  src/components/Friend/RenderGroupDetail.js
  src/components/Friend/RenderGroupLists.js
  src/components/Friend/RenderUserLists.js
  src/components/Miscellaneous/EditSection.js
  src/screens/Friend/AddBlockedUserScreen.js
  src/screens/Friend/AddFriendScreen.js
  src/screens/Friend/AddGroupMemberScreen.js
  src/screens/Friend/BlockedUserListScreen.js
  src/screens/Friend/EditGroupMemberScreen.js
  src/screens/Friend/EditPendingGroupMemberScreen.js
  src/screens/Friend/FriendInfoScreen.js
  src/screens/Friend/FriendListScreen.js
  src/screens/Friend/FriendRequestsReceivedScreen.js
  src/screens/Friend/FriendRequestsSentScreen.js
  src/screens/Friend/GroupInfoScreen.js
  src/screens/Friend/GroupListScreen.js
  src/screens/Friend/GroupRequestInfoScreen.js
  src/screens/Friend/GroupRequestsScreen.js
  src/styles/GeneralStyles.js
  src/styles/InfoStyles.js
  src/styles/ListStyles.js
Labels: enhancement

#103 Anime styling
  __test__/ui-test/Friend/__snapshots__/GroupInfoScreen.test.js.snap
  __test__/ui-test/Friend/__snapshots__/GroupRequestInfoScreen.test.js.snap
  src/components/Anime/AnimeCard.js
  src/components/Anime/AnimeCollection.js
  src/screens/Anime/FavoriteAnimeScreen.js
  src/screens/Anime/RecommendationScreen.js
  src/styles/GeneralStyles.js
Labels: enhancement

#102 Chat section styling
  __test__/ui-test/Chat/ChatButtonGroup.test.js
  __test__/ui-test/Chat/__snapshots__/ActiveChatLists.test.js.snap
  __test__/ui-test/Chat/__snapshots__/ChatDetailScreen.test.js.snap
  __test__/ui-test/Chat/__snapshots__/GroupChatDetailScreen.test.js.snap
  src/components/Chat/ActiveChatLists.js
  src/components/Chat/ChatBar.js
  src/components/Chat/ChatButtonGroup.js
  src/components/Chat/ChatHeader.js
  src/components/Friend/GroupMemberList.js
  src/components/Friend/RenderFriendFavorites.js
  src/components/Friend/RenderGroupLists.js
  src/components/Friend/RenderUserLists.js
  src/screens/Chat/AddChatScreen.js
  src/screens/Chat/ChatDetailScreen.js
  src/screens/Chat/ChatListScreen.js
  src/screens/Chat/GroupChatDetailScreen.js
  src/screens/Chat/GroupChatListScreen.js
  src/screens/Friend/BlockedUserListScreen.js
  src/screens/Friend/FriendListScreen.js
  src/screens/Friend/FriendRequestsReceivedScreen.js
  src/screens/Friend/FriendRequestsSentScreen.js
  src/screens/Friend/GroupListScreen.js
  src/screens/Friend/GroupRequestsScreen.js
  src/styles/ChatStyles.js
Labels: enhancement

#105 Auth loading
  __test__/unit-test/Authentication/HandleAuthentication.test.js
  src/components/Miscellaneous/AnimatedInput.js
  src/screens/ForgotPasswordScreen.js
  src/screens/LoginScreen.js
  src/screens/SignupScreen.js
  src/services/Authentication/HandleAuthentication.js
Labels: enhancement

#107 Profile styling
  src/components/Profile/GenresList.js
  src/components/Profile/HandleFavoriteButton.js
  src/components/Profile/PastPostCard.js
  src/components/Profile/RenderFavorites.js
  src/screens/Profile/EditGenreScreen.js
  src/screens/Profile/PastPostsScreen.js
  src/screens/Profile/ProfileHomeScreen.js
Labels: enhancement

#109 Standalone app deployment
  app.config.js
  google-services.json
Labels: enhancement

#110 Anime unit test
  __test__/ui-test/Anime/AnimeHomeScreen.test.js
  __test__/ui-test/Anime/AnimeResultScreen.test.js
  __test__/ui-test/Anime/FavoriteAnimeScreen.test.js
  __test__/ui-test/Anime/RecommendationScreen.test.js
  __test__/ui-test/Anime/RenderRecommendation.test.js
  __test__/ui-test/Anime/__snapshots__/AnimeHomeScreen.test.js.snap
  __test__/ui-test/Anime/__snapshots__/AnimeResultScreen.test.js.snap
  __test__/ui-test/Anime/__snapshots__/FavoriteAnimeScreen.test.js.snap
  __test__/ui-test/Anime/__snapshots__/RecommendationScreen.test.js.snap
  __test__/ui-test/Anime/__snapshots__/RenderRecommendation.test.js.snap
  src/components/Anime/RenderRecommendation.js
  src/screens/Anime/AnimeHomeScreen.js
  src/screens/Anime/AnimeResultScreen.js
  src/screens/Anime/FavoriteAnimeScreen.js
  src/screens/Anime/RecommendationScreen.js
Labels: testing

#114 Add recommendation count
  recommendation_model/model.pkl
  recommendation_model/model.py
Labels: enhancement

#116 Bug fixes
  __test__/unit-test/Authentication/HandleAuthentication.test.js
  src/components/Anime/RenderRecommendation.js
  src/components/Forum/ForumComment/RenderCommentScreen.js
  src/components/Forum/ForumPost/RenderPostScreen.js
  src/components/Miscellaneous/AnimatedInput.js
  src/screens/Profile/ProfileHomeScreen.js
  src/services/Anime/FetchRecommendations.js
  src/services/Authentication/HandleAuthentication.js
  src/services/Forum/NotifyAllFollowers.js
  src/services/Profile/FetchUserInfo.js
Labels: bug

#117 Profile UI test
  __test__/ui-test/Profile/EditGenreScreen.test.js
  __test__/ui-test/Profile/GenresList.test.js
  __test__/ui-test/Profile/PastPostCard.test.js
  __test__/ui-test/Profile/PastPostList.test.js
  __test__/ui-test/Profile/PastPostsScreen.test.js
  __test__/ui-test/Profile/ProfileHomeScreen.test.js
  __test__/ui-test/Profile/RenderFavorites.test.js
  __test__/ui-test/Profile/__snapshots__/PastPostList.test.js.snap
  __test__/ui-test/Profile/__snapshots__/ProfileHomeScreen.test.js.snap
  src/components/Profile/GenresList.js
  src/components/Profile/PastPostCard.js
  src/components/Profile/RenderFavorites.js
  src/screens/Profile/EditGenreScreen.js
  src/screens/Profile/PastPostsScreen.js
  src/screens/Profile/ProfileHomeScreen.js
Labels: testing

#120 Minor enchancements
  __test__/ui-test/Anime/AnimeHomeScreen.test.js
  __test__/ui-test/Anime/__snapshots__/AnimeHomeScreen.test.js.snap
  __test__/ui-test/Chat/ChatDetailScreen.test.js
  __test__/ui-test/Chat/GroupChatDetailScreen.test.js
  __test__/ui-test/Chat/__snapshots__/ChatDetailScreen.test.js.snap
  __test__/ui-test/Chat/__snapshots__/GroupChatDetailScreen.test.js.snap
  __test__/ui-test/Forum/CommentList.test.js
  __test__/ui-test/Forum/FollowedForumScreen.test.js
  __test__/ui-test/Forum/ForumHomeScreen.test.js
  __test__/ui-test/Forum/ForumScreen.test.js
  src/assets/funfacts.js
  src/components/Forum/ForumComment/CommentList.js
  src/components/Forum/ForumComment/RenderCommentScreen.js
  src/components/Forum/ForumList.js
  src/components/Forum/ForumPost/PostList.js
  src/components/Forum/ForumPost/RenderPostScreen.js
  src/components/Forum/RenderManageForumDetails.js
  src/components/Miscellaneous/LoaderAnimation.js
  src/screens/Anime/AnimeHomeScreen.js
  src/screens/Chat/ChatListScreen.js
  src/screens/Chat/GroupChatListScreen.js
  src/screens/Forum/FollowedForumScreen.js
  src/screens/Forum/ForumHomeScreen.js
  src/screens/Forum/ForumScreen.js
  src/screens/Friend/AddFriendScreen.js
  src/screens/Friend/AddGroupMemberScreen.js
  src/screens/Friend/BlockedUserListScreen.js
  src/screens/Friend/EditGroupMemberScreen.js
  src/screens/Friend/EditPendingGroupMemberScreen.js
  src/screens/Friend/FriendListScreen.js
  src/screens/Friend/FriendRequestsReceivedScreen.js
  src/screens/Friend/FriendRequestsSentScreen.js
  src/screens/Friend/GroupListScreen.js
  src/screens/Friend/GroupRequestsScreen.js
  src/screens/HomeScreen.js
  src/screens/Profile/EditGenreScreen.js
Labels: enhancement
