Repository sugiyem/Chattoku, pull requests merged in 2022-06, with the labels that each got.

#28 Fix iOS testing error
  README.md
  app.config.js
Labels: bug

#34 Add documentation folder
  README.md
  doc/Chattoku User's Guide.pdf
  doc/Milestone Reports/Milestone 1 Report.pdf
  doc/Project Proposal.pdf
Labels: documentation

#38 Add some unit test
  __test__/Helper.js
  __test__/unit-test/Anime/FetchFavoriteAnime.test.js
  __test__/unit-test/Anime/HandleFavorite.test.js
  __test__/unit-test/Authentication/CheckUsername.test.js
  __test__/unit-test/Authentication/HandleAuthentication.test.js
  __test__/unit-test/Friend/FetchFriendStatus.test.js
  __test__/unit-test/Friend/FetchGroup.test.js
  __test__/unit-test/Friend/HandleFriend.test.js
  __test__/unit-test/Friend/HandleGroup.test.js
  package-lock.json
  package.json
  src/services/Friend/FetchFriendStatus.js
  src/services/Friend/FetchGroup.js
  src/services/Friend/HandleGroup.js
  yarn.lock
Labels: testing

#37 Add recommendation system
  __test__/ui-test/Anime/AnimeCard.test.js
  __test__/ui-test/Anime/AnimeList.test.js
  __test__/ui-test/Anime/AnimeSearchBar.test.js
  __test__/ui-test/Anime/__snapshots__/AnimeSearchBar.test.js.snap
  __test__/unit-test/Anime/AnimeAndGenreConverter.test.js
  __test__/unit-test/Anime/AnimeFetch.test.js
  __test__/unit-test/Anime/FetchRecommendations.test.js
  __test__/unit-test/Anime/HandleFavorite.test.js
  src/components/Anime/AnimeCard.js
  src/components/Anime/AnimeCollection.js
  src/components/Anime/AnimeList.js
  src/components/Anime/AnimeSearchBar.js
  src/components/Anime/RenderRecommendation.js
  src/components/Miscellaneous/Loading.js
  src/constants/MyAnimeList.js
  src/screens/Anime/AnimeHomeScreen.js
  src/screens/Anime/AnimeResultScreen.js
  src/screens/Anime/AnimeScreen.js
  src/screens/Anime/FavAnimeRecommendationScreen.js
  src/screens/Anime/FavGenreRecommendationScreen.js
  src/screens/Anime/FavoriteAnimeScreen.js
  src/screens/Anime/RecommendationScreen.js
  src/services/Anime/AnimeAndGenreConverter.js
  src/services/Anime/AnimeFetch.js
  src/services/Anime/FetchRecommendations.js
  src/services/Anime/HandleFavorite.js
  src/styles/GeneralStyles.js
Labels: enhancement

#45 Add Previous Posts
  src/components/Forum/ForumComment/CommentCard.js
  src/components/Forum/ForumComment/CommentList.js
  src/components/Forum/ForumManagement/BannedUsersList.js
  src/components/Forum/ForumPost/LikeBar.js
  src/components/Forum/ForumPost/PostCard.js
  src/components/Forum/ForumPost/PostList.js
  src/components/Profile/PastPostCard.js
  src/components/Profile/PastPostList.js
  src/screens/Forum/ForumPostScreen.js
  src/screens/Forum/ForumScreen.js
  src/screens/Profile/PastPostsScreen.js
  src/screens/Profile/ProfileHomeScreen.js
  src/screens/Profile/ProfileScreen.js
  src/services/Forum/FetchPreviousPosts.js
  src/services/Forum/HandleBannedUsers.js
  src/services/Forum/HandleForumPost.js
  src/services/Profile/FetchUserInfo.js
  yarn.lock
Labels: bug, enhancement

#47 Milestone 2 review
  README.md
  __test__/__snapshots__/App.test.js.snap
  __test__/unit-test/Authentication/CheckCredentials.test.js
  __test__/unit-test/Authentication/CheckUsername.test.js
  __test__/unit-test/Authentication/HandleAuthentication.test.js
  __test__/unit-test/Miscellaneous/HandleNotification.test.js
  recommendation_model/Procfile
  recommendation_model/app.py
  recommendation_model/assets/sample-request.png
  recommendation_model/dataset/mal_top3000.csv
  recommendation_model/model.pkl
  recommendation_model/model.py
  recommendation_model/requirements.txt
  recommendation_model/runtime.txt
  recommendation_model/scraper/package-lock.json
  recommendation_model/scraper/package.json
  recommendation_model/scraper/scraper.js
  recommendation_model/templates/index.html
  src/screens/Anime/AnimeHomeScreen.js
  src/screens/Anime/AnimeResultScreen.js
  src/screens/ForgotPasswordScreen.js
  src/screens/LoginScreen.js
  src/screens/SignupScreen.js
  src/services/Authentication/AuthNavigation.js
  src/services/Authentication/CheckCredentials.js
  src/services/Authentication/HandleAuthentication.js
  src/services/Forum/HandleForum.js
  src/styles/AuthStyles.js
  src/styles/GeneralStyles.js
Labels: bug, documentation, testing
